function anison_init(){var anison_player=jQuery("#anison_player");var anison_btns=jQuery("#anison .player_btn");var anison_start=jQuery("#anison_start");var anison_stop=jQuery("#anison_stop");var list_320="http://s1.radio.ru-hoster.com:8000/AniSonFM(320)";anison_start.click(function(){anison_player.jPlayer("clearMedia");anison_player.jPlayer("setMedia",{mp3:list_320});anison_player.jPlayer("play",0);anison_btns.toggleClass("active");});anison_stop.click(function(){anison_player.jPlayer("clearMedia");anison_btns.toggleClass("active");});anison_player.jPlayer({ready:function(event){$(this).jPlayer("clearMedia");},swfPath:"http://anison.fm/js/jplayer/Jplayer.swf"});};function f_duration(j_duration){var j_time="";var j_hours=Math.floor(j_duration/3600);var j_mod_mins=j_duration%3600;var j_mins=Math.floor(j_mod_mins/60);var j_secs=Math.floor(j_mod_mins%60);if(j_hours>0){j_time+=j_hours+":";if(j_mins<10){j_mins="0"+ j_mins;}}
if(j_secs<10){j_secs="0"+ j_secs;}
j_time+=j_mins+":"+ j_secs;return j_time;}
var j_air_pause=0;function f_timer(duration){clearInterval(this.counter);var j_duration=jQuery("#duration");j_duration.html(f_duration(duration));this.counter=window.setInterval(function(){duration=duration- 1;if(duration>0){j_air_pause=0;j_duration.html(f_duration(duration));}else{clearInterval(this.counter);j_air_pause++;j_duration.html("0:00");var j_timeout=500;if(j_air_pause<6){window.setTimeout(function(){f_update();},500);}}},1000)}
var update_timer=20000;function f_update(){var j_url="http://anison.fm/status.php?widget=true";var j_options=jQuery("#anison").attr("options");if(j_options=="nofollow"){j_url+="&nofollow=true";}
jQuery.ajax({type:"GET",dataType:"jsonp",url:j_url,success:function(data,textStatus){var j_listeners=jQuery("#listeners");var listeners=data.listeners;j_listeners.html(listeners);var j_on_air=jQuery("#on_air");var on_air=strip_tags(data.on_air,'<span>');j_on_air.html(on_air);var duration=data.duration;f_timer(parseInt(duration));}})}
function f_update_circle(){clearInterval(this.update);this.update=window.setInterval(function(){f_update();},update_timer);}
jQuery(document).ready(function(){var anison=jQuery("#anison");var j_style="\n";var anison_w=parseInt(anison.attr("width"));if(anison_w>100){var volume_block_w=anison_w- 31;var volume_area_w=anison_w- 78;var volume_level_w=anison_w- 82;var jp_audio_w=anison_w- 39;j_style+="<style>\n";j_style+="  #anison.radio_info {min-width: "+ anison_w+"px; width: "+ anison_w+"px;}\n";j_style+="    #anison.radio_info .icon-volume-block {width: "+ volume_block_w+"px;}\n";j_style+="    #anison.radio_info .icon-volume-area {width: "+ volume_area_w+"px;}\n";j_style+="    #anison.radio_info .icon-volume-level {width: "+ volume_level_w+"px;}\n";j_style+="      #anison.radio_info .anison_player_container .jp-audio {width: "+ jp_audio_w+"px;}\n";j_style+="</style>\n";}
var j_options=jQuery("#anison").attr("options");if(j_options=="nofollow"){var rel=" rel='nofollow'";}else{var rel="";}
var anison_code='\n';if(jQuery.jPlayer){anison_code+='<div class="anison_player_container">\n';anison_code+='  <div id="anison_player"></div>\n';anison_code+='  <div id="anison_start" title="&#1057;&#1090;&#1072;&#1088;&#1090;" class="player_btn icon-btn-ball start active">\n';anison_code+='    <i class="icon-play"></i>\n';anison_code+='  </div>\n';anison_code+='  <div id="anison_stop" title="&#1057;&#1090;&#1086;&#1087;" class="player_btn icon-btn-ball stop">\n';anison_code+='    <i class="icon-stop"></i>\n';anison_code+='  </div>\n';anison_code+='  <div id="jp_container_1" class="jp-audio icon-volume-block top-banner">\n';anison_code+='    <a href="javascript:void(0);" title="&#1042;&#1099;&#1082;&#1083;&#1102;&#1095;&#1080;&#1090;&#1100; &#1079;&#1074;&#1091;&#1082;" class="mute_btn jp-mute" rel="nofollow">\n';anison_code+='      <i class="icon-volume"></i>\n';anison_code+='    </a>\n';anison_code+='    <a href="javascript:void(0);" title="&#1042;&#1082;&#1083;&#1102;&#1095;&#1080;&#1090;&#1100; &#1079;&#1074;&#1091;&#1082;" class="mute_btn jp-unmute" rel="nofollow">\n';anison_code+='      <i class="icon-unvolume"></i>\n';anison_code+='    </a>\n';anison_code+='    <div class="jp-volume-bar icon-volume-area">\n';anison_code+='      <div class="jp-volume-bar-value icon-volume-level">\n';anison_code+='        <i class="volume_dot icon-volume-dot"></i>\n';anison_code+='      </div>\n';anison_code+='    </div>\n';anison_code+='  </div>\n';anison_code+='</div>\n';}
anison_code+='<div class="anison_text">\n';anison_code+='  <span>&#1057;&#1083;&#1091;&#1096;&#1072;&#1090;&#1100; &#1074; &#1087;&#1083;&#1077;&#1077;&#1088;&#1077;:</span>\n';anison_code+='  <a href="http://anison.fm/anison.m3u"'+ rel+'><img src="http://anison.fm/images/players_icon.png"/></a>\n';anison_code+='</div>\n';anison_code+='<div class="track_info">\n';anison_code+='  <div class="track_info_str">\n';anison_code+='     <span id="on_air"></span>\n';anison_code+='  </div>\n';anison_code+='  <div class="track_info_str">\n';anison_code+='    <span class="text">&#1044;&#1086; &#1082;&#1086;&#1085;&#1094;&#1072; &#1090;&#1088;&#1077;&#1082;&#1072; &#1086;&#1089;&#1090;&#1072;&#1083;&#1086;&#1089;&#1100;:</span>\n';anison_code+='    <span id="duration"></span>\n';anison_code+='  </div>\n';anison_code+='  <div class="track_info_str">\n';anison_code+='    <span id="listeners"></span>\n';anison_code+='  </div>\n';anison_code+='</div>\n';anison_code+=j_style;anison.addClass("radio_info").html(anison_code);if(jQuery.jPlayer){anison_init();}
f_update();f_update_circle();});function strip_tags(input,allowed){allowed=(((allowed||'')+'').toLowerCase().match(/<[a-z][a-z0-9]*>/g)||[]).join('');var tags=/<\/?([a-z][a-z0-9]*)\b[^>]*>/gi,commentsAndPhpTags=/<!--[\s\S]*?-->|<\?(?:php)?[\s\S]*?\?>/gi;return input.replace(commentsAndPhpTags,'').replace(tags,function($0,$1){return allowed.indexOf('<'+ $1.toLowerCase()+'>')>-1?$0:'';});}